# fly.toml app configuration file generated for fullstacktest on 2023-08-02T06:12:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstacktest"
primary_region = "gru"

[env]
  PORT = "8080" # adicione isto

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]